Add controllers
gyngazov/java-shareit pull request #1
Opened 2023-07-03 08:15 UTC by gyngazov

2023-07-03 15:33 UTC, EugeneLenkevich approved these changes
Привет, Лев, спасибо за PR

В целом все отлично :)
Несколько совсем небольших косметических моментов, посмотри комментарии ниже, пожалуйста

2023-07-03 15:33 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text.trim().isEmpty()) {
Если text будет null то мы получим ошибку, тут бы проверку добавить :)

2023-07-03 15:33 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    Item getItemById(int itemId);
В именах методов Item можно уже и не упоминать, и так понятно по имени сервиса. Код чутка покороче без потери читаемости :)
Item getById(int itemId);

2023-07-03 15:33 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        } else {
else кстати можно уже и не писать, в случае исключения мы из метода выйдем и этот код точно так же будет пропущен :)

2023-07-03 15:33 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        userService.getUser(userId);
Вот тут не совсем понятно что происходит, мы ищем пользователя но никуда его не присваиваем. Предположу что так делается проверка на существование, но, мне кажется, что это не особо очевидно, если это так то лучше записат как то так

if (!userStrorage.isExist(item)) {
    //бросаем исключения и тп
}

2023-07-03 15:33 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        itemStorage.updateItem(updateItem);
1. А не более ли надежно сохраять ту запись что у нас в хранилище, а не ту что в метод пришла, допустим у нас в сущности в хранилище больше полей чем в сущности обновения,часть данных или потрется или другой метод должен будет нам вообще все данные передавать изначально :)
2. Можно кстати вот такую запись использовать если надо проверить что-то на null и обновить поле

Optional.ofNullable(itemUpdate.getName()).ifPresent(bdItem::setName)

2023-07-03 15:33 UTC, EugeneLenkevich requested changes
.

2023-07-04 07:40 UTC, gyngazov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        itemStorage.updateItem(updateItem);
Евгений, не понял 1. Может не "сохранять", а "возвращать"? Если "возвращать", то зачем пользователю старая запись, если именно ее он хочет обновить?
2. У item нет нужных сетов, поэтому для апдейта он формируется конструктором.

2023-07-04 07:47 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        itemStorage.updateItem(updateItem);
я к чему. вот смотри. мы полностью конструируем новую запись и перезаписываем ее

![image](https://github.com/gyngazov/java-shareit/assets/109306643/c925c7f3-b396-4ce5-a83d-5760605f83e1)

я же предлагаю не перезаписывать все, а дописать в уже существующую необходимые поля. Потом появяться новые поля в сущности, а в апдейт их не добавят, например. В итоге мы будем терять данные. Да и пользователь же обычно обновляет не всю запись, а какие то ее поля

2023-07-04 08:08 UTC, EugeneLenkevich approved these changes
Все супер, спасибо!

2023-07-04 08:09 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        itemStorage.updateItem(updateItem);
Это все к чему. В реальной жизни сущности гораздо сложнее и обновляются они не полностью, а частично. ЖДопустим есть какие то технические поля, отметки и пр. При таком подходже мы будем вынуждены прокидывать все состояние олностью через сущность-обновление. Имей этот момент в виду :)

2023-07-04 08:23 UTC, gyngazov commented
Изменил. Так?

2023-07-04 08:28 UTC, EugeneLenkevich commented
> Изменил. Так?

Ага, все верно

2023-07-04 08:32 UTC, merged