Add bookings
gyngazov/java-shareit pull request #2
Opened 2023-07-20 11:04 UTC by gyngazov

2023-07-20 14:47 UTC, EugeneLenkevich requested changes
Привет, Лев, спасибо за PR

Отличная работа, оставил совсем небольшие коментарии :)

2023-07-20 14:47 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
С этой аннотацией надо поаккурантей. Она генерирует equals и hashCode на основании всех полей. 
Однако, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа). 

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.
 
Плюс еще некоторые поля могут быть ленивыми коллекциями и в момент обращения бдут генерироваться sql-запросы, которые и не нужны в данный момент

Т.е. надо или переопределить руками или указать через аннотации как генерировать эти методы :)

2023-07-20 14:47 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findByNameOrDescriptionContainingIgnoreCaseAndAvailableTrue(
Чтобы не мучаться с такими длинными именами можно с помощью аннотации @Query указать самостоятельно sql-запрос  :)

2023-07-20 14:47 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (isMyItem(item, userId)) {
А не проще было бы сразу в запросе отфильтровывать чужие записи и не загружать их в приложение. Так будет и более эффективно и более безопасно :)

2023-07-20 14:47 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getMyBookings(int userId, String state) {
String state

А не проще тут передавать enum, можно сразу в контроллере переменную такого типа использовать :)

2023-07-20 14:47 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case ("ALL"):
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<String, Supplier> handlers = ...
handlers.put("ALL", this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2023-07-20 14:47 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private final Set<Integer> foundUsers = new HashSet<>();
Вообще для кэширования есть готовые библиотеки, ehcache например, вообще, обычно лучше готовые решения использовать, их протестировали вдоль и поперек сотни пользователей, но это все явно вне рамок этого курса :)

https://habr.com/ru/articles/465667/

2023-07-21 12:54 UTC, gyngazov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (isMyItem(item, userId)) {
Евгений, уточни "в запросе отфильтровывать чужие записи".
Сейчас в бд идем за бронированиями только когда запрос от владельца. Это и есть фильтр. Иначе вообще не идем в бд за бронированиями.

2023-07-21 12:57 UTC, gyngazov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getMyBookings(int userId, String state) {
Я изначально енум сделал, но с енумом не правльно обрабатывался UNSUPPORTED_STATUS. Не выкидывалась 404 и UNSUPPORTED_STATUS проходил как дефолт ALL. Больше не знал как починить тест и сделал в лоб через стринг.

2023-07-21 13:14 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getMyBookings(int userId, String state) {
Имею в виду вот что, есть вот такая проверка, по которой возвращается пустой список если она не пройдена

![image](https://github.com/gyngazov/java-shareit/assets/109306643/65a54d24-5d30-41dd-a034-cfbb04faaab5)


Так вот, можено же в сам sql-запрос добавить аналогичное условие

2023-07-21 19:40 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getMyBookings(int userId, String state) {
Ух,не под тем же коментарием ответил, это вот сюда :)

![image](https://github.com/gyngazov/java-shareit/assets/109306643/6cecfccd-5a46-4b25-affd-042981a48174)

2023-07-21 19:42 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-07-23 04:29 UTC, merged